### ISSUE TITLE
[Setting] ISSUE TEMPLATE 추가 

### ISSUE THREAD

**Issue by deslog** [Trip-Money/TripMoney_iOS#13]
### Feature 설명

초기에 Feature/Bug 탬플릿만 넣어뒀는데, Design, Setting 과 관련된 이슈 탬플릿도 필요한 것 같아서 추가하려고 합니다,,,

**Comment by GODNOEL** [comment]
오 좋습니다. 브라운 고생많으셨어요..!!ㅠㅠ
